apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-custom.fullname" . }}
  labels:
    {{- include "wordpress-custom.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wordpress-custom.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wordpress-custom.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: wordpress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ if eq .Values.database.type "internal" }}{{ include "wordpress-custom.fullname" . }}-mysql{{ else }}{{ .Values.database.host }}{{ end }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.database.name }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.database.user }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress-custom.fullname" . }}-secret
                  key: database-password
            - name: WORDPRESS_CONFIG_EXTRA
              value: |
                define('WP_HOME','https://{{ .Values.app.domain }}');
                define('WP_SITEURL','https://{{ .Values.app.domain }}');
                define('FORCE_SSL_ADMIN', true);
          volumeMounts:
            - name: wordpress-storage
              mountPath: /var/www/html
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /wp-admin/install.php
              port: http
            initialDelaySeconds: 180
            timeoutSeconds: 30
            periodSeconds: 30
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /wp-admin/install.php
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 30
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: {{ include "wordpress-custom.fullname" . }}-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- if eq .Values.database.type "internal" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-custom.fullname" . }}-mysql
  labels:
    {{- include "wordpress-custom.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wordpress-custom.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        {{- include "wordpress-custom.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress-custom.fullname" . }}-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.database.name }}
            - name: MYSQL_USER
              value: {{ .Values.database.user }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress-custom.fullname" . }}-secret
                  key: database-password
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: {{ include "wordpress-custom.fullname" . }}-mysql-pvc
{{- end }}
