{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wordpress-custom.fullname" . }}
  labels:
    {{- include "wordpress-custom.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.className }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- if .Values.ssl.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.ssl.issuer }}
    {{- end }}
spec:
  {{- if .Values.ssl.enabled }}
  tls:
    - hosts:
        - {{ .Values.app.domain }}
      secretName: {{ include "wordpress-custom.fullname" . }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.app.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "wordpress-custom.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
