apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress-custom.fullname" . }}-pvc
  labels:
    {{- include "wordpress-custom.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}

{{- if eq .Values.database.type "internal" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress-custom.fullname" . }}-mysql-pvc
  labels:
    {{- include "wordpress-custom.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
  {{- if .Values.mysql.persistence.storageClass }}
  storageClassName: {{ .Values.mysql.persistence.storageClass }}
  {{- end }}
{{- end }}
